# Generated by Django 4.0.5 on 2022-08-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_rename_grade_number_user_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='grade',
            new_name='grade_number',
        ),
    ]
