# Generated by Django 4.0.5 on 2022-08-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_rename_grade_user_grade_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pw_access_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
