# Generated by Django 4.0.5 on 2022-08-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_user_pw_access_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='usage',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
